# prometheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'


scrape_configs:
  - job_name: 'prometheus'
    target_groups:
    - targets: ['192.168.1.12:9090']
  - job_name: 'node-exporter'
    target_groups:
    - targets: ['192.168.1.12:9100']
  - job_name: 'cAdvisor'
    target_groups:
    - targets: ['192.168.1.12:8080']
